site_name: yeastdnnexplorer
site_description: "A collection of objects and functions to work with calling cards sequencing tools"
site_author: "ben mueller <email@email.com>, chase mateusiak <chasem@wustl.edu>, michael brent <brent@wustl.edu>"
site_url: "https://brentlab.github.io/yeastdnnexplorer/"
repo_url: "https://github.com/brentlab/yeastdnnexplorer"
repo_name: "yeastdnnexplorer"
edit_uri: "edit/master/docs/"
watch: ['yeastdnnexplorer', 'docs']

theme:
  name: material

plugins:
- search
- autorefs
- section-index
- mknotebooks
- mkdocstrings:
    handlers:
          python:
            paths: [yeastdnnexplorer]  # search packages in the src folder
            merge_init_into_class: True
            options:
              docstring_style: 'sphinx'

nav:
- Home: index.md
- Tutorials:
  - Generate In-silico Data: tutorials/generate_in_silico_data.ipynb
  - Database Interface: tutorials/database_interface.ipynb
  - Hyperparameter Sweep: tutorials/hyperparameter_sweep.ipynb
  - Lightning Crash Course: tutorials/lightning_crash_course.ipynb
  - Testing Model Metrics: tutorials/testing_model_metrics.ipynb
  - Visualizing and Testing Data Generation Methods: tutorials/visualizing_and_testing_data_generation_methods.ipynb
- API:
  - Data Loaders:
    - Synthetic Data Loader: data_loaders/synthetic_data_loader.md
    - Real Data Loader: data_loaders/real_data_loader.md
  - Models:
    - ml_models/customizable_model.md
    - ml_models/metrics_compute_nrmse.md
    - ml_models/metrics_smse.md
    - ml_models/simple_model.md
  - Probability Models:
    - probability_models/default_perturbation_effect_adjustment_function.md
    - probability_models/GenePopulation.md
    - probability_models/generate_binding_effects.md
    - Generate Gene Population: probability_models/generate_gene_population.md
    - probability_models/generate_perturbation_effects.md
    - probability_models/generate_pvalues.md
    - probability_models/perturbation_effect_adjustment_function_with_tf_relationships_boolean_logic.md
    - probability_models/perturbation_effect_adjustment_function_with_tf_relationships.md
  - Database Interface:
    - Records Only Classes:
      - interface/BindingManualQCAPI.md
      - interface/DataSourceAPI.md
      - interface/ExpressionManualQCAPI.md
      - interface/FileFormatAPI.md
      - interface/GenomicFeatureAPI.md
      - interface/RegulatorAPI.md
    - Records and Files Classes:
      - interface/BindingAPI.md
      - interface/CallingCardsBackgroundAPI.md
      - interface/ExpressionAPI.md
      - interface/PromoterSetAPI.md
      - interface/PromoterSetSigAPI.md
    - Developer Classes:
      - interface/AbstractAPI.md
      - interface/AbstractRecordsAndFilesAPI.md
      - interface/AbstractRecordsOnlyAPI.md
      - interface/Cache.md
      - interface/ParamsDict.md

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
